# Google app engine deployment
runtime: nodejs14
env: standard
entrypoint: node index.js
automatic_scaling:
  max_instances: 3
env_variables:
  DATABASE_SERVICE: "firebase"
  AUTOGRADING_SERVER: "https://grader.speedrunethereum.com:54727"
  BG_BACKEND: "https://buidlguidl-v3.ew.r.appspot.com"
handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
